### ISSUE TITLE
Example blog using Reem

### ISSUE THREAD

**Issue by luckypoem** [andrejewski/reem#2]
hi.

i read over https://github.com/andrejewski/reem ,feel it's very complex for novices.so can u upload a demo blog's source code??

thank u very much.

**Comment by andrejewski** [comment]
Reem is complex, no doubt. I have no problem creating an example project, but I would like to know where you got stumped. This is not a dig at you, the documentation should be helpful and it is the problem. I would like to know where things get hairy from your perspective.

**Comment by luckypoem** [comment]
hi.
cd /usr/local
mkdir reem-site
cd reem-site

root@AR:/usr/local/reem-site# ls
root@AR:/usr/local/reem-site# reem --init
root@AR:/usr/local/reem-site# ls
layout  output  reemfile.js  source
root@AR:/usr/local/reem-site# 
root@AR:/usr/local/reem-site# ls layout
root@AR:/usr/local/reem-site# ls source
root@AR:/usr/local/reem-site#

the layout and source dir are all empty,so here i'm stuck.i don't know why they are empty.
then can u upload a demo blog's source code??
thank u very much

**Comment by luckypoem** [comment]
hi.

have u uploaded a demo blog's source code?
expecting it

thank u very much

**Comment by andrejewski** [comment]
I have added a minimal example folder to this project, demonstrating its simplest use. I recommend using a static site generator with a stronger community if you are looking to get started in general making these kinds of sites.

**Comment by luckypoem** [comment]
it's still too simple:
root@localhost:/usr/local/reem-site/example# ls
layout        output      package.json  source
node_modules  output-old  reemfile.js   yarn.lock
root@localhost:/usr/local/reem-site/example# ls source
hello-world.md
root@localhost:/usr/local/reem-site/example# 

there is no index.md in /usr/local/reem-site/example/source/??
it's not pragmatical.
